apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xyal7zzf1-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:92803626193f45e8dcf68eff3127bb323ad53ee7@sha256:5179d9e779847d277cae0fb9ff0ab6dc88ce830e2d6b11ba692e9ac2a30446fc
          name: container-image
